language: ruby
rvm:
  - 2.2

before_install:
  - sudo apt-get install libcurl3-dev

script:
  - bundle exec rake test

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: true
